/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CaseStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Resolved' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Time = IDL.Int;
export const Case = IDL.Record({
  'id' : IDL.Nat,
  'status' : CaseStatus,
  'issueType' : IDL.Text,
  'title' : IDL.Text,
  'lastUpdated' : Time,
  'createdDate' : Time,
  'description' : IDL.Text,
  'assignedLawyer' : IDL.Opt(IDL.Principal),
});
export const UploadedDocument = IDL.Record({
  'id' : IDL.Nat,
  'analysisSummary' : IDL.Text,
  'filename' : IDL.Text,
  'uploadDate' : Time,
});
export const GuidanceHistory = IDL.Record({
  'id' : IDL.Nat,
  'queryText' : IDL.Text,
  'timestamp' : Time,
  'resultSummary' : IDL.Text,
});
export const Feedback = IDL.Record({
  'comment' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
  'principalId' : IDL.Principal,
});
export const LoginRecord = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'principalId' : IDL.Principal,
});
export const WaitlistEntry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ChatbotEntry = IDL.Record({
  'id' : IDL.Nat,
  'tip' : IDL.Text,
  'title' : IDL.Text,
  'documents' : IDL.Vec(IDL.Text),
  'cost' : IDL.Text,
  'icon' : IDL.Text,
  'whatToDo' : IDL.Text,
  'successRate' : IDL.Text,
  'timeRequired' : IDL.Text,
  'topicKey' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
  'lawyerType' : IDL.Text,
  'intro' : IDL.Text,
});
export const LawyerProfile = IDL.Record({
  'name' : IDL.Text,
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
  'barNumber' : IDL.Text,
  'location' : IDL.Text,
  'principalId' : IDL.Principal,
});
export const Lawyer = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'reviewsCount' : IDL.Nat,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'specialization' : IDL.Text,
  'rating' : IDL.Float64,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'principalId' : IDL.Principal,
});
export const Language = IDL.Variant({
  'Telugu' : IDL.Null,
  'Kannada' : IDL.Null,
  'Tamil' : IDL.Null,
  'Bengali' : IDL.Null,
  'Hindi' : IDL.Null,
  'English' : IDL.Null,
});

export const idlService = IDL.Service({
  'addCase' : IDL.Func([Case], [IDL.Record({ 'id' : IDL.Nat })], []),
  'addDocument' : IDL.Func(
      [UploadedDocument],
      [IDL.Record({ 'id' : IDL.Nat })],
      [],
    ),
  'addGuidanceHistory' : IDL.Func(
      [GuidanceHistory],
      [IDL.Record({ 'id' : IDL.Nat })],
      [],
    ),
  'addWaitlistEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCaseToLawyer' : IDL.Func(
      [IDL.Record({ 'lawyerPrincipal' : IDL.Principal, 'caseId' : IDL.Nat })],
      [IDL.Bool],
      [],
    ),
  'deleteLawyer' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'deleteUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllLoginRecords' : IDL.Func([], [IDL.Vec(LoginRecord)], ['query']),
  'getAllWaitlistEntries' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
  'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getChatbotEntries' : IDL.Func([], [IDL.Vec(ChatbotEntry)], ['query']),
  'getDocuments' : IDL.Func([], [IDL.Vec(UploadedDocument)], ['query']),
  'getGuidanceHistory' : IDL.Func([], [IDL.Vec(GuidanceHistory)], ['query']),
  'getLawyerCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getLawyerProfile' : IDL.Func([], [IDL.Opt(LawyerProfile)], ['query']),
  'getLawyerProfiles' : IDL.Func([], [IDL.Vec(Lawyer)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyWaitlistEntry' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WaitlistEntry)],
      ['query'],
    ),
  'getUserFeedback' : IDL.Func([], [IDL.Opt(Feedback)], ['query']),
  'getUserLanguage' : IDL.Func([], [IDL.Opt(Language)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'listAllLawyers' : IDL.Func([], [IDL.Vec(LawyerProfile)], ['query']),
  'listAllUsersAdmin' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'registerLawyer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'registerLawyerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'registerOrUpdateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'resetChatbotEntries' : IDL.Func([], [IDL.Bool], []),
  'setUserLanguage' : IDL.Func([Language], [], []),
  'submitFeedback' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateCaseStatus' : IDL.Func(
      [IDL.Record({ 'caseId' : IDL.Nat, 'newStatus' : CaseStatus })],
      [IDL.Bool],
      [],
    ),
  'updateChatbotEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CaseStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Resolved' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Time = IDL.Int;
  const Case = IDL.Record({
    'id' : IDL.Nat,
    'status' : CaseStatus,
    'issueType' : IDL.Text,
    'title' : IDL.Text,
    'lastUpdated' : Time,
    'createdDate' : Time,
    'description' : IDL.Text,
    'assignedLawyer' : IDL.Opt(IDL.Principal),
  });
  const UploadedDocument = IDL.Record({
    'id' : IDL.Nat,
    'analysisSummary' : IDL.Text,
    'filename' : IDL.Text,
    'uploadDate' : Time,
  });
  const GuidanceHistory = IDL.Record({
    'id' : IDL.Nat,
    'queryText' : IDL.Text,
    'timestamp' : Time,
    'resultSummary' : IDL.Text,
  });
  const Feedback = IDL.Record({
    'comment' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
    'principalId' : IDL.Principal,
  });
  const LoginRecord = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'principalId' : IDL.Principal,
  });
  const WaitlistEntry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ChatbotEntry = IDL.Record({
    'id' : IDL.Nat,
    'tip' : IDL.Text,
    'title' : IDL.Text,
    'documents' : IDL.Vec(IDL.Text),
    'cost' : IDL.Text,
    'icon' : IDL.Text,
    'whatToDo' : IDL.Text,
    'successRate' : IDL.Text,
    'timeRequired' : IDL.Text,
    'topicKey' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
    'lawyerType' : IDL.Text,
    'intro' : IDL.Text,
  });
  const LawyerProfile = IDL.Record({
    'name' : IDL.Text,
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
    'barNumber' : IDL.Text,
    'location' : IDL.Text,
    'principalId' : IDL.Principal,
  });
  const Lawyer = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'reviewsCount' : IDL.Nat,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'specialization' : IDL.Text,
    'rating' : IDL.Float64,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'principalId' : IDL.Principal,
  });
  const Language = IDL.Variant({
    'Telugu' : IDL.Null,
    'Kannada' : IDL.Null,
    'Tamil' : IDL.Null,
    'Bengali' : IDL.Null,
    'Hindi' : IDL.Null,
    'English' : IDL.Null,
  });
  
  return IDL.Service({
    'addCase' : IDL.Func([Case], [IDL.Record({ 'id' : IDL.Nat })], []),
    'addDocument' : IDL.Func(
        [UploadedDocument],
        [IDL.Record({ 'id' : IDL.Nat })],
        [],
      ),
    'addGuidanceHistory' : IDL.Func(
        [GuidanceHistory],
        [IDL.Record({ 'id' : IDL.Nat })],
        [],
      ),
    'addWaitlistEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'assignCaseToLawyer' : IDL.Func(
        [IDL.Record({ 'lawyerPrincipal' : IDL.Principal, 'caseId' : IDL.Nat })],
        [IDL.Bool],
        [],
      ),
    'deleteLawyer' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'deleteUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllLoginRecords' : IDL.Func([], [IDL.Vec(LoginRecord)], ['query']),
    'getAllWaitlistEntries' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
    'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getChatbotEntries' : IDL.Func([], [IDL.Vec(ChatbotEntry)], ['query']),
    'getDocuments' : IDL.Func([], [IDL.Vec(UploadedDocument)], ['query']),
    'getGuidanceHistory' : IDL.Func([], [IDL.Vec(GuidanceHistory)], ['query']),
    'getLawyerCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getLawyerProfile' : IDL.Func([], [IDL.Opt(LawyerProfile)], ['query']),
    'getLawyerProfiles' : IDL.Func([], [IDL.Vec(Lawyer)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyWaitlistEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WaitlistEntry)],
        ['query'],
      ),
    'getUserFeedback' : IDL.Func([], [IDL.Opt(Feedback)], ['query']),
    'getUserLanguage' : IDL.Func([], [IDL.Opt(Language)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'listAllLawyers' : IDL.Func([], [IDL.Vec(LawyerProfile)], ['query']),
    'listAllUsersAdmin' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'registerLawyer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'registerLawyerLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'registerOrUpdateUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'resetChatbotEntries' : IDL.Func([], [IDL.Bool], []),
    'setUserLanguage' : IDL.Func([Language], [], []),
    'submitFeedback' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateCaseStatus' : IDL.Func(
        [IDL.Record({ 'caseId' : IDL.Nat, 'newStatus' : CaseStatus })],
        [IDL.Bool],
        [],
      ),
    'updateChatbotEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };