/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Case {
  'id' : bigint,
  'status' : CaseStatus,
  'issueType' : string,
  'title' : string,
  'lastUpdated' : Time,
  'createdDate' : Time,
  'description' : string,
  'assignedLawyer' : [] | [Principal],
}
export type CaseStatus = { 'Active' : null } |
  { 'Resolved' : null } |
  { 'Pending' : null };
export interface Feedback {
  'comment' : string,
  'timestamp' : Time,
  'rating' : bigint,
  'principalId' : Principal,
}
export interface GuidanceHistory {
  'id' : bigint,
  'queryText' : string,
  'timestamp' : Time,
  'resultSummary' : string,
}
export type Language = { 'Telugu' : null } |
  { 'Kannada' : null } |
  { 'Tamil' : null } |
  { 'Bengali' : null } |
  { 'Hindi' : null } |
  { 'English' : null };
export interface Lawyer {
  'id' : bigint,
  'bio' : string,
  'reviewsCount' : bigint,
  'name' : string,
  'available' : boolean,
  'specialization' : string,
  'rating' : number,
  'location' : string,
}
export interface LawyerProfile {
  'name' : string,
  'specialization' : string,
  'phone' : string,
  'barNumber' : string,
  'location' : string,
  'principalId' : Principal,
}
export type Time = bigint;
export interface UploadedDocument {
  'id' : bigint,
  'analysisSummary' : string,
  'filename' : string,
  'uploadDate' : Time,
}
export interface UserProfile {
  'name' : string,
  'phone' : string,
  'principalId' : Principal,
}
export interface _SERVICE {
  'addCase' : ActorMethod<[Case], { 'id' : bigint }>,
  'addDocument' : ActorMethod<[UploadedDocument], { 'id' : bigint }>,
  'addGuidanceHistory' : ActorMethod<[GuidanceHistory], { 'id' : bigint }>,
  'assignCaseToLawyer' : ActorMethod<
    [{ 'lawyerPrincipal' : Principal, 'caseId' : bigint }],
    boolean
  >,
  'deleteLawyer' : ActorMethod<[Principal], boolean>,
  'deleteUser' : ActorMethod<[Principal], boolean>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getCases' : ActorMethod<[], Array<Case>>,
  'getDocuments' : ActorMethod<[], Array<UploadedDocument>>,
  'getGuidanceHistory' : ActorMethod<[], Array<GuidanceHistory>>,
  'getLawyerCases' : ActorMethod<[], Array<Case>>,
  'getLawyerProfile' : ActorMethod<[], [] | [LawyerProfile]>,
  'getLawyerProfiles' : ActorMethod<[], Array<Lawyer>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserFeedback' : ActorMethod<[], [] | [Feedback]>,
  'getUserLanguage' : ActorMethod<[], [] | [Language]>,
  'initialize' : ActorMethod<[], undefined>,
  'listAllLawyers' : ActorMethod<[], Array<LawyerProfile>>,
  'listAllUsersAdmin' : ActorMethod<[], Array<UserProfile>>,
  'registerLawyer' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'registerOrUpdateUser' : ActorMethod<[string, string], boolean>,
  'setUserLanguage' : ActorMethod<[Language], undefined>,
  'submitFeedback' : ActorMethod<[bigint, string], boolean>,
  'updateCaseStatus' : ActorMethod<
    [{ 'caseId' : bigint, 'newStatus' : CaseStatus }],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];