/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CaseStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Resolved' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Time = IDL.Int;
export const Case = IDL.Record({
  'id' : IDL.Nat,
  'status' : CaseStatus,
  'issueType' : IDL.Text,
  'title' : IDL.Text,
  'createdDate' : Time,
  'description' : IDL.Text,
});
export const UploadedDocument = IDL.Record({
  'id' : IDL.Nat,
  'analysisSummary' : IDL.Text,
  'filename' : IDL.Text,
  'uploadDate' : Time,
});
export const GuidanceHistory = IDL.Record({
  'id' : IDL.Nat,
  'queryText' : IDL.Text,
  'timestamp' : Time,
  'resultSummary' : IDL.Text,
});
export const Lawyer = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'reviewsCount' : IDL.Nat,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'specialization' : IDL.Text,
  'rating' : IDL.Float64,
  'location' : IDL.Text,
});
export const Language = IDL.Variant({
  'Telugu' : IDL.Null,
  'Kannada' : IDL.Null,
  'Tamil' : IDL.Null,
  'Bengali' : IDL.Null,
  'Hindi' : IDL.Null,
  'English' : IDL.Null,
});

export const idlService = IDL.Service({
  'addCase' : IDL.Func([Case], [], []),
  'addDocument' : IDL.Func([UploadedDocument], [], []),
  'addGuidanceHistory' : IDL.Func([GuidanceHistory], [], []),
  'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getDocuments' : IDL.Func([], [IDL.Vec(UploadedDocument)], ['query']),
  'getGuidanceHistory' : IDL.Func([], [IDL.Vec(GuidanceHistory)], ['query']),
  'getLawyerProfiles' : IDL.Func([], [IDL.Vec(Lawyer)], ['query']),
  'getUserLanguage' : IDL.Func([], [IDL.Opt(Language)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'setUserLanguage' : IDL.Func([Language], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CaseStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Resolved' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Time = IDL.Int;
  const Case = IDL.Record({
    'id' : IDL.Nat,
    'status' : CaseStatus,
    'issueType' : IDL.Text,
    'title' : IDL.Text,
    'createdDate' : Time,
    'description' : IDL.Text,
  });
  const UploadedDocument = IDL.Record({
    'id' : IDL.Nat,
    'analysisSummary' : IDL.Text,
    'filename' : IDL.Text,
    'uploadDate' : Time,
  });
  const GuidanceHistory = IDL.Record({
    'id' : IDL.Nat,
    'queryText' : IDL.Text,
    'timestamp' : Time,
    'resultSummary' : IDL.Text,
  });
  const Lawyer = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'reviewsCount' : IDL.Nat,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'specialization' : IDL.Text,
    'rating' : IDL.Float64,
    'location' : IDL.Text,
  });
  const Language = IDL.Variant({
    'Telugu' : IDL.Null,
    'Kannada' : IDL.Null,
    'Tamil' : IDL.Null,
    'Bengali' : IDL.Null,
    'Hindi' : IDL.Null,
    'English' : IDL.Null,
  });
  
  return IDL.Service({
    'addCase' : IDL.Func([Case], [], []),
    'addDocument' : IDL.Func([UploadedDocument], [], []),
    'addGuidanceHistory' : IDL.Func([GuidanceHistory], [], []),
    'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getDocuments' : IDL.Func([], [IDL.Vec(UploadedDocument)], ['query']),
    'getGuidanceHistory' : IDL.Func([], [IDL.Vec(GuidanceHistory)], ['query']),
    'getLawyerProfiles' : IDL.Func([], [IDL.Vec(Lawyer)], ['query']),
    'getUserLanguage' : IDL.Func([], [IDL.Opt(Language)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'setUserLanguage' : IDL.Func([Language], [], []),
  });
};

export const init = ({ IDL }) => { return []; };