/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Case {
  'id' : bigint,
  'status' : CaseStatus,
  'issueType' : string,
  'title' : string,
  'createdDate' : Time,
  'description' : string,
}
export type CaseStatus = { 'Active' : null } |
  { 'Resolved' : null } |
  { 'Pending' : null };
export interface GuidanceHistory {
  'id' : bigint,
  'queryText' : string,
  'timestamp' : Time,
  'resultSummary' : string,
}
export type Language = { 'Telugu' : null } |
  { 'Kannada' : null } |
  { 'Tamil' : null } |
  { 'Bengali' : null } |
  { 'Hindi' : null } |
  { 'English' : null };
export interface Lawyer {
  'id' : bigint,
  'bio' : string,
  'reviewsCount' : bigint,
  'name' : string,
  'available' : boolean,
  'specialization' : string,
  'rating' : number,
  'location' : string,
}
export type Time = bigint;
export interface UploadedDocument {
  'id' : bigint,
  'analysisSummary' : string,
  'filename' : string,
  'uploadDate' : Time,
}
export interface _SERVICE {
  'addCase' : ActorMethod<[Case], undefined>,
  'addDocument' : ActorMethod<[UploadedDocument], undefined>,
  'addGuidanceHistory' : ActorMethod<[GuidanceHistory], undefined>,
  'getCases' : ActorMethod<[], Array<Case>>,
  'getDocuments' : ActorMethod<[], Array<UploadedDocument>>,
  'getGuidanceHistory' : ActorMethod<[], Array<GuidanceHistory>>,
  'getLawyerProfiles' : ActorMethod<[], Array<Lawyer>>,
  'getUserLanguage' : ActorMethod<[], [] | [Language]>,
  'initialize' : ActorMethod<[], undefined>,
  'setUserLanguage' : ActorMethod<[Language], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];