/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UploadedDocument {
    id: bigint;
    analysisSummary: string;
    filename: string;
    uploadDate: Time;
}
export interface Lawyer {
    id: bigint;
    bio: string;
    reviewsCount: bigint;
    name: string;
    available: boolean;
    specialization: string;
    rating: number;
    location: string;
}
export type Time = bigint;
export interface GuidanceHistory {
    id: bigint;
    queryText: string;
    timestamp: Time;
    resultSummary: string;
}
export interface Case {
    id: bigint;
    status: CaseStatus;
    issueType: string;
    title: string;
    createdDate: Time;
    description: string;
}
export enum CaseStatus {
    Active = "Active",
    Resolved = "Resolved",
    Pending = "Pending"
}
export enum Language {
    Telugu = "Telugu",
    Kannada = "Kannada",
    Tamil = "Tamil",
    Bengali = "Bengali",
    Hindi = "Hindi",
    English = "English"
}
export interface backendInterface {
    addCase(newCase: Case): Promise<void>;
    addDocument(doc: UploadedDocument): Promise<void>;
    addGuidanceHistory(entry: GuidanceHistory): Promise<void>;
    getCases(): Promise<Array<Case>>;
    getDocuments(): Promise<Array<UploadedDocument>>;
    getGuidanceHistory(): Promise<Array<GuidanceHistory>>;
    getLawyerProfiles(): Promise<Array<Lawyer>>;
    getUserLanguage(): Promise<Language | null>;
    initialize(): Promise<void>;
    setUserLanguage(lang: Language): Promise<void>;
}
import type { Case as _Case, CaseStatus as _CaseStatus, Language as _Language, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCase(arg0: Case): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCase(to_candid_Case_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCase(to_candid_Case_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDocument(arg0: UploadedDocument): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0);
            return result;
        }
    }
    async addGuidanceHistory(arg0: GuidanceHistory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGuidanceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGuidanceHistory(arg0);
            return result;
        }
    }
    async getCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCases();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCases();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocuments(): Promise<Array<UploadedDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocuments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocuments();
            return result;
        }
    }
    async getGuidanceHistory(): Promise<Array<GuidanceHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuidanceHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuidanceHistory();
            return result;
        }
    }
    async getLawyerProfiles(): Promise<Array<Lawyer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLawyerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLawyerProfiles();
            return result;
        }
    }
    async getUserLanguage(): Promise<Language | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLanguage();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLanguage();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async setUserLanguage(arg0: Language): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserLanguage(to_candid_Language_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserLanguage(to_candid_Language_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CaseStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseStatus): CaseStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Case_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Case): Case {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Language]): Language | null {
    return value.length === 0 ? null : from_candid_Language_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CaseStatus;
    issueType: string;
    title: string;
    createdDate: _Time;
    description: string;
}): {
    id: bigint;
    status: CaseStatus;
    issueType: string;
    title: string;
    createdDate: Time;
    description: string;
} {
    return {
        id: value.id,
        status: from_candid_CaseStatus_n8(_uploadFile, _downloadFile, value.status),
        issueType: value.issueType,
        title: value.title,
        createdDate: value.createdDate,
        description: value.description
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Telugu: null;
} | {
    Kannada: null;
} | {
    Tamil: null;
} | {
    Bengali: null;
} | {
    Hindi: null;
} | {
    English: null;
}): Language {
    return "Telugu" in value ? Language.Telugu : "Kannada" in value ? Language.Kannada : "Tamil" in value ? Language.Tamil : "Bengali" in value ? Language.Bengali : "Hindi" in value ? Language.Hindi : "English" in value ? Language.English : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Resolved: null;
} | {
    Pending: null;
}): CaseStatus {
    return "Active" in value ? CaseStatus.Active : "Resolved" in value ? CaseStatus.Resolved : "Pending" in value ? CaseStatus.Pending : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Case>): Array<Case> {
    return value.map((x)=>from_candid_Case_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CaseStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): _CaseStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Case_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Case): _Case {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: CaseStatus;
    issueType: string;
    title: string;
    createdDate: Time;
    description: string;
}): {
    id: bigint;
    status: _CaseStatus;
    issueType: string;
    title: string;
    createdDate: _Time;
    description: string;
} {
    return {
        id: value.id,
        status: to_candid_CaseStatus_n3(_uploadFile, _downloadFile, value.status),
        issueType: value.issueType,
        title: value.title,
        createdDate: value.createdDate,
        description: value.description
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    Telugu: null;
} | {
    Kannada: null;
} | {
    Tamil: null;
} | {
    Bengali: null;
} | {
    Hindi: null;
} | {
    English: null;
} {
    return value == Language.Telugu ? {
        Telugu: null
    } : value == Language.Kannada ? {
        Kannada: null
    } : value == Language.Tamil ? {
        Tamil: null
    } : value == Language.Bengali ? {
        Bengali: null
    } : value == Language.Hindi ? {
        Hindi: null
    } : value == Language.English ? {
        English: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): {
    Active: null;
} | {
    Resolved: null;
} | {
    Pending: null;
} {
    return value == CaseStatus.Active ? {
        Active: null
    } : value == CaseStatus.Resolved ? {
        Resolved: null
    } : value == CaseStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
