/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UploadedDocument {
    id: bigint;
    analysisSummary: string;
    filename: string;
    uploadDate: Time;
}
export interface Lawyer {
    id: bigint;
    bio: string;
    reviewsCount: bigint;
    name: string;
    available: boolean;
    specialization: string;
    rating: number;
    location: string;
}
export interface WaitlistEntry {
    name: string;
    email: string;
    timestamp: Time;
    phone: string;
}
export type Time = bigint;
export interface Feedback {
    comment: string;
    timestamp: Time;
    rating: bigint;
    principalId: Principal;
}
export interface LoginRecord {
    name: string;
    role: string;
    timestamp: Time;
    phone: string;
    principalId: Principal;
}
export interface LawyerProfile {
    name: string;
    specialization: string;
    phone: string;
    barNumber: string;
    location: string;
    principalId: Principal;
}
export interface GuidanceHistory {
    id: bigint;
    queryText: string;
    timestamp: Time;
    resultSummary: string;
}
export interface ChatbotEntry {
    id: bigint;
    tip: string;
    title: string;
    documents: Array<string>;
    cost: string;
    icon: string;
    whatToDo: string;
    successRate: string;
    timeRequired: string;
    topicKey: string;
    keywords: Array<string>;
    lawyerType: string;
    intro: string;
}
export interface UserProfile {
    name: string;
    phone: string;
    principalId: Principal;
}
export interface Case {
    id: bigint;
    status: CaseStatus;
    issueType: string;
    title: string;
    lastUpdated: Time;
    createdDate: Time;
    description: string;
    assignedLawyer?: Principal;
}
export enum CaseStatus {
    Active = "Active",
    Resolved = "Resolved",
    Pending = "Pending"
}
export enum Language {
    Telugu = "Telugu",
    Kannada = "Kannada",
    Tamil = "Tamil",
    Bengali = "Bengali",
    Hindi = "Hindi",
    English = "English"
}
export interface backendInterface {
    addCase(newCase: Case): Promise<{
        id: bigint;
    }>;
    addDocument(doc: UploadedDocument): Promise<{
        id: bigint;
    }>;
    addGuidanceHistory(entry: GuidanceHistory): Promise<{
        id: bigint;
    }>;
    addWaitlistEntry(name: string, email: string, phone: string): Promise<boolean>;
    assignCaseToLawyer(arg0: {
        lawyerPrincipal: Principal;
        caseId: bigint;
    }): Promise<boolean>;
    deleteLawyer(principalId: Principal): Promise<boolean>;
    deleteUser(principalId: Principal): Promise<boolean>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAllLoginRecords(): Promise<Array<LoginRecord>>;
    getAllWaitlistEntries(): Promise<Array<WaitlistEntry>>;
    getCases(): Promise<Array<Case>>;
    getChatbotEntries(): Promise<Array<ChatbotEntry>>;
    getDocuments(): Promise<Array<UploadedDocument>>;
    getGuidanceHistory(): Promise<Array<GuidanceHistory>>;
    getLawyerCases(): Promise<Array<Case>>;
    getLawyerProfile(): Promise<LawyerProfile | null>;
    getLawyerProfiles(): Promise<Array<Lawyer>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyWaitlistEntry(email: string): Promise<WaitlistEntry | null>;
    getUserFeedback(): Promise<Feedback | null>;
    getUserLanguage(): Promise<Language | null>;
    initialize(): Promise<void>;
    listAllLawyers(): Promise<Array<LawyerProfile>>;
    listAllUsersAdmin(): Promise<Array<UserProfile>>;
    registerLawyer(name: string, phone: string, barNumber: string, specialization: string, location: string): Promise<boolean>;
    registerLawyerLogin(name: string, phone: string): Promise<boolean>;
    registerOrUpdateUser(name: string, phone: string): Promise<boolean>;
    resetChatbotEntries(): Promise<boolean>;
    setUserLanguage(lang: Language): Promise<void>;
    submitFeedback(rating: bigint, comment: string): Promise<boolean>;
    updateCaseStatus(arg0: {
        caseId: bigint;
        newStatus: CaseStatus;
    }): Promise<boolean>;
    updateChatbotEntry(id: bigint, intro: string, whatToDo: string, documents: Array<string>, lawyerType: string, cost: string, timeRequired: string, successRate: string, tip: string): Promise<boolean>;
}
import type { Case as _Case, CaseStatus as _CaseStatus, Feedback as _Feedback, Language as _Language, LawyerProfile as _LawyerProfile, Time as _Time, UserProfile as _UserProfile, WaitlistEntry as _WaitlistEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCase(arg0: Case): Promise<{
        id: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addCase(to_candid_Case_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCase(to_candid_Case_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDocument(arg0: UploadedDocument): Promise<{
        id: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0);
            return result;
        }
    }
    async addGuidanceHistory(arg0: GuidanceHistory): Promise<{
        id: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addGuidanceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGuidanceHistory(arg0);
            return result;
        }
    }
    async addWaitlistEntry(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addWaitlistEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWaitlistEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCaseToLawyer(arg0: {
        lawyerPrincipal: Principal;
        caseId: bigint;
    }): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCaseToLawyer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCaseToLawyer(arg0);
            return result;
        }
    }
    async deleteLawyer(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLawyer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLawyer(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return result;
        }
    }
    async getAllLoginRecords(): Promise<Array<LoginRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLoginRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLoginRecords();
            return result;
        }
    }
    async getAllWaitlistEntries(): Promise<Array<WaitlistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWaitlistEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWaitlistEntries();
            return result;
        }
    }
    async getCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCases();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCases();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatbotEntries(): Promise<Array<ChatbotEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatbotEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatbotEntries();
            return result;
        }
    }
    async getDocuments(): Promise<Array<UploadedDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocuments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocuments();
            return result;
        }
    }
    async getGuidanceHistory(): Promise<Array<GuidanceHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuidanceHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuidanceHistory();
            return result;
        }
    }
    async getLawyerCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLawyerCases();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLawyerCases();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLawyerProfile(): Promise<LawyerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLawyerProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLawyerProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLawyerProfiles(): Promise<Array<Lawyer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLawyerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLawyerProfiles();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWaitlistEntry(arg0: string): Promise<WaitlistEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWaitlistEntry(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWaitlistEntry(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserFeedback(): Promise<Feedback | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFeedback();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFeedback();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserLanguage(): Promise<Language | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLanguage();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLanguage();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async listAllLawyers(): Promise<Array<LawyerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllLawyers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllLawyers();
            return result;
        }
    }
    async listAllUsersAdmin(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsersAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsersAdmin();
            return result;
        }
    }
    async registerLawyer(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerLawyer(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerLawyer(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async registerLawyerLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerLawyerLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerLawyerLogin(arg0, arg1);
            return result;
        }
    }
    async registerOrUpdateUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOrUpdateUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOrUpdateUser(arg0, arg1);
            return result;
        }
    }
    async resetChatbotEntries(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resetChatbotEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetChatbotEntries();
            return result;
        }
    }
    async setUserLanguage(arg0: Language): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserLanguage(to_candid_Language_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserLanguage(to_candid_Language_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitFeedback(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1);
            return result;
        }
    }
    async updateCaseStatus(arg0: {
        caseId: bigint;
        newStatus: CaseStatus;
    }): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaseStatus(to_candid_record_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaseStatus(to_candid_record_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateChatbotEntry(arg0: bigint, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChatbotEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChatbotEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
}
function from_candid_CaseStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseStatus): CaseStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Case_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Case): Case {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LawyerProfile]): LawyerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WaitlistEntry]): WaitlistEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Feedback]): Feedback | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Language]): Language | null {
    return value.length === 0 ? null : from_candid_Language_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CaseStatus;
    issueType: string;
    title: string;
    lastUpdated: _Time;
    createdDate: _Time;
    description: string;
    assignedLawyer: [] | [Principal];
}): {
    id: bigint;
    status: CaseStatus;
    issueType: string;
    title: string;
    lastUpdated: Time;
    createdDate: Time;
    description: string;
    assignedLawyer?: Principal;
} {
    return {
        id: value.id,
        status: from_candid_CaseStatus_n8(_uploadFile, _downloadFile, value.status),
        issueType: value.issueType,
        title: value.title,
        lastUpdated: value.lastUpdated,
        createdDate: value.createdDate,
        description: value.description,
        assignedLawyer: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.assignedLawyer))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Telugu: null;
} | {
    Kannada: null;
} | {
    Tamil: null;
} | {
    Bengali: null;
} | {
    Hindi: null;
} | {
    English: null;
}): Language {
    return "Telugu" in value ? Language.Telugu : "Kannada" in value ? Language.Kannada : "Tamil" in value ? Language.Tamil : "Bengali" in value ? Language.Bengali : "Hindi" in value ? Language.Hindi : "English" in value ? Language.English : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Resolved: null;
} | {
    Pending: null;
}): CaseStatus {
    return "Active" in value ? CaseStatus.Active : "Resolved" in value ? CaseStatus.Resolved : "Pending" in value ? CaseStatus.Pending : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Case>): Array<Case> {
    return value.map((x)=>from_candid_Case_n6(_uploadFile, _downloadFile, x));
}
function to_candid_CaseStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): _CaseStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Case_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Case): _Case {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: CaseStatus;
    issueType: string;
    title: string;
    lastUpdated: Time;
    createdDate: Time;
    description: string;
    assignedLawyer?: Principal;
}): {
    id: bigint;
    status: _CaseStatus;
    issueType: string;
    title: string;
    lastUpdated: _Time;
    createdDate: _Time;
    description: string;
    assignedLawyer: [] | [Principal];
} {
    return {
        id: value.id,
        status: to_candid_CaseStatus_n3(_uploadFile, _downloadFile, value.status),
        issueType: value.issueType,
        title: value.title,
        lastUpdated: value.lastUpdated,
        createdDate: value.createdDate,
        description: value.description,
        assignedLawyer: value.assignedLawyer ? candid_some(value.assignedLawyer) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    caseId: bigint;
    newStatus: CaseStatus;
}): {
    caseId: bigint;
    newStatus: _CaseStatus;
} {
    return {
        caseId: value.caseId,
        newStatus: to_candid_CaseStatus_n3(_uploadFile, _downloadFile, value.newStatus)
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    Telugu: null;
} | {
    Kannada: null;
} | {
    Tamil: null;
} | {
    Bengali: null;
} | {
    Hindi: null;
} | {
    English: null;
} {
    return value == Language.Telugu ? {
        Telugu: null
    } : value == Language.Kannada ? {
        Kannada: null
    } : value == Language.Tamil ? {
        Tamil: null
    } : value == Language.Bengali ? {
        Bengali: null
    } : value == Language.Hindi ? {
        Hindi: null
    } : value == Language.English ? {
        English: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): {
    Active: null;
} | {
    Resolved: null;
} | {
    Pending: null;
} {
    return value == CaseStatus.Active ? {
        Active: null
    } : value == CaseStatus.Resolved ? {
        Resolved: null
    } : value == CaseStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
